name: Build & Release Electron Binary

on:
  push:

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      - run: npm install
      - run: npm run build
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*
