name: Build & Release Electron Binary

on:
  push:

jobs:
  build:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.0
      - run: npm ci
      - run: npm run build
      - run: for i in bin/*/; do zip -r "${i%/}.zip" "$i"; done
      - uses: softprops/action-gh-release@v1
        with:
          files: |
            bin/*.zip
